=== Forcecat01/Datapack/data/xsd/attendance.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="AttendanceItem" minOccurs="0" maxOccurs="28"/>
				<xs:element name="vip-item" type="AttendanceVipItem" minOccurs="0" maxOccurs="4"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="AttendanceItem">
		<xs:complexContent>
			<xs:extension base="ItemInfo">
				<xs:attribute name="highlight" type="xs:boolean" default="false"/>
				<xs:attribute name="cafe-points" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AttendanceVipItem">
		<xs:complexContent>
			<xs:extension base="AttendanceItem">
				<xs:attribute name="vip-level" type="xs:byte" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== Forcecat01/Datapack/data/attendance.xml
<?xml version="1.0" encoding="UTF-8"?>

<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://l2j.org"
	  xsi:schemaLocation="http://l2j.org xsd/attendance.xsd">

	<item id="29647" count="3" /> <!-- Attendance Coin -->
	<item id="71437"/> <!-- Shining jewel box -->
	<item id="91780" count="3" /> <!-- Battle scroll  -->
	<item id="29566"/> <!-- Attendance XP Rune -->
	<item id="29584" count="3" /> <!-- XP/SP Scroll - Medium -->
	<item id="10649" count="2" /> <!-- Feather of blessing -->
	<item id="90045" count="31" highlight="true" /> <!-- L-coin -->
	<item id="29647" count="3" /> <!-- Attendance Coin -->
	<item id="71437"/> <!-- Shining jewel box -->
	<item id="91780" count="3" /> <!-- Battle scroll  -->
	<item id="29566"/> <!-- Attendance XP Rune -->
	<item id="29650" count="3" /> <!-- XP/SP Scroll - High -->
	<item id="10649" count="3" /> <!-- Feather of blessing -->
	<item id="90045" count="31" highlight="true"/> <!-- L-coin -->
	<item id="29647" count="3" /> <!-- Attendance Coin -->
	<item id="71437" count="2" /> <!-- Shining jewel box -->
	<item id="91780" count="6" /> <!-- Battle scroll  -->
	<item id="29566" count="2" /> <!-- Attendance XP Rune -->
	<item id="29650" count="6" /> <!-- XP/SP Scroll - High -->
	<item id="10649" count="4" /> <!-- Feather of blessing -->
	<item id="90045" count="31" highlight="true" /> <!-- L-coin -->
	<item id="29647" count="3" /> <!-- Attendance Coin -->
	<item id="71437" count="2" /> <!-- Shining jewel box -->
	<item id="91780" count="6" /> <!-- Battle scroll  -->
	<item id="29566" count="2" /> <!-- Attendance XP Rune -->
	<item id="29650" count="6" /> <!-- XP/SP Scrolsssl - High -->
	<item id="10649" count="5" /> <!-- Feather of blessing -->
	<item id="90045" count="31" highlight="true"/> <!-- L-coin -->

	<vip-item id="57" count="1000" vip-level="1"/>
	<vip-item id="57" count="10000" vip-level="2"/>
	<vip-item id="57" count="100000" vip-level="3"/>
	<vip-item id="57" count="1000000" vip-level="4"/>
</list>
